version: "3.7"
services:
  app:
    container_name: emiteai
    build: src
    networks:
      - "emiteai-network"
    tty: true
    ports:
      - 8080:8080
networks:
  make-magic-network:
    driver: bridge